export type CenterAvailability = "open" | "limited" | "full" | "closed";
export type CenterVerificationStatus = "reference" | "verified" | "stale" | "retired";
export type CenterAccessibility = { wheelchair?: boolean; medicalSupport?: boolean | string; accessibleToilet?: boolean; notes?: string };
export type DirectionDestination = { id: string; name: string; kind: "evacuation" | "response"; detail: string; phone?: string; latitude?: number; longitude?: number; address?: string; status: string; availableSlots?: number; operationalStatus?: CenterAvailability; accessibility?: CenterAccessibility | null; verificationStatus?: CenterVerificationStatus; sourceName?: string; sourceReference?: string | null; freshUntil?: Date | string | null; isCurrent?: boolean; searchTerms?: string[] };
export const responseDirections: DirectionDestination[] = [
  { id: "balangiga-lgu", name: "Balangiga LGU operations", kind: "response", detail: "Municipal coordination reference", address: "Balangiga Municipal Hall, Balangiga, Eastern Samar, Philippines", status: "Confirm before travel" },
  { id: "eastern-samar-pdrrmo", name: "Eastern Samar PDRRMO", kind: "response", detail: "Provincial disaster-response coordination", address: "Provincial Capitol of Eastern Samar, Borongan City, Eastern Samar, Philippines", phone: "0917 117 0807", status: "Call before travel" },
];
export const fallbackEvacuationDestination: DirectionDestination = { id: "balangiga-roster", name: "Balangiga evacuation reference", kind: "evacuation", detail: "LGU-designated site confirmation required", latitude: 11.1086, longitude: 125.3877, phone: "0917 117 0807", status: "Verify designation", availableSlots: 0, operationalStatus: "limited", accessibility: { wheelchair: false, medicalSupport: false }, verificationStatus: "reference", sourceName: "Balangiga readiness reference", isCurrent: false, searchTerms: ["Balangiga", "Poblacion", "town center"] };
export const handoffDestination = (destination: DirectionDestination) => destination.latitude !== undefined && destination.longitude !== undefined ? `${destination.latitude},${destination.longitude}` : encodeURIComponent(destination.address ?? destination.name);
export function filterDirectionsDestinations(destinations: DirectionDestination[], query: string) { const normalized = query.trim().toLocaleLowerCase(); if (!normalized) return destinations; return destinations.filter((destination) => [destination.name, destination.detail, destination.address ?? "", ...(destination.searchTerms ?? [])].join(" ").toLocaleLowerCase().includes(normalized)); }
export function centerAvailability(destination: DirectionDestination) { if (destination.kind !== "evacuation") return { marker: "R", label: destination.status, tone: "response" as const }; const status = destination.operationalStatus ?? "limited"; const slots = destination.availableSlots ?? 0; const label = status === "open" ? `${slots} slots open` : status === "limited" ? `Limited · ${slots} slots` : status === "full" ? "Full" : "Closed"; return { marker: status === "open" ? String(slots) : status === "limited" ? String(slots) : status === "full" ? "FULL" : "X", label, tone: status }; }
export function evacuationAccessDetails(destination: DirectionDestination) {
  const accessibility = destination.accessibility;
  const wheelchair = accessibility?.wheelchair === true ? "Wheelchair access available" : "Wheelchair access not confirmed";
  const medicalSupport = typeof accessibility?.medicalSupport === "string" ? accessibility.medicalSupport : accessibility?.medicalSupport ? "Medical support available" : "Medical support: confirm with LGU";
  const contact = destination.phone ? `Call ${destination.phone}` : "Contact: confirm with LGU";
  return { contact, wheelchair, medicalSupport, accessibleToilet: accessibility?.accessibleToilet === true ? "Accessible toilet available" : null, notes: accessibility?.notes ?? null };
}
export function centerTrustDetails(destination: DirectionDestination) { if (destination.kind !== "evacuation") return { label: "Confirm before travel", detail: destination.status, tone: "reference" as const }; const status = destination.verificationStatus ?? "reference"; if (status === "verified" && destination.isCurrent !== false) return { label: "LGU verified", detail: destination.sourceName ? `Source: ${destination.sourceName}` : "Current operational record", tone: "verified" as const }; if (status === "stale") return { label: "Update may be stale", detail: destination.sourceName ? `Last source: ${destination.sourceName}` : "Confirm current conditions with the LGU", tone: "stale" as const }; if (status === "retired") return { label: "No longer active", detail: "Choose another evacuation center", tone: "retired" as const }; return { label: "Reference only", detail: destination.sourceName ? `Confirm with ${destination.sourceName}` : "Confirm with the Balangiga LGU", tone: "reference" as const }; }
export type HouseholdReadinessNeeds = { wheelchair: boolean; medicalSupport: boolean };
export function rankAlternativeCenters(destinations: DirectionDestination[], unavailableId: string | null, needs: HouseholdReadinessNeeds) { return destinations.filter((destination) => destination.kind === "evacuation" && destination.id !== unavailableId && destination.operationalStatus !== "full" && destination.operationalStatus !== "closed" && (destination.availableSlots ?? 0) > 0 && destination.verificationStatus !== "retired").sort((a, b) => { const score = (destination: DirectionDestination) => { const trust = centerTrustDetails(destination); let total = (destination.availableSlots ?? 0); if (trust.tone === "verified") total += 10000; if (needs.wheelchair && destination.accessibility?.wheelchair) total += 2000; if (needs.medicalSupport && destination.accessibility?.medicalSupport) total += 1200; if (trust.tone === "stale") total -= 800; return total; }; return score(b) - score(a); }); }
export function centerCapacityWarning(destination: DirectionDestination | undefined) { return Boolean(destination?.kind === "evacuation" && (destination.operationalStatus === "full" || destination.operationalStatus === "closed")); }
export function summarizeDirectionLegs(legs: Array<{ distance?: { value?: number }; duration?: { value?: number } }>) { const meters = legs.reduce((total, leg) => total + (leg.distance?.value ?? 0), 0); const seconds = legs.reduce((total, leg) => total + (leg.duration?.value ?? 0), 0); return { meters, seconds, kilometers: Math.round(meters / 100) / 10, minutes: Math.max(1, Math.round(seconds / 60)) }; }
export type DirectionStep = { instruction: string; meters: number; seconds: number };
export function extractDirectionSteps(legs: Array<{ steps?: Array<{ instructions?: string; html_instructions?: string; distance?: { value?: number }; duration?: { value?: number } }> }>): DirectionStep[] { return legs.flatMap((leg) => (leg.steps ?? []).map((step) => ({ instruction: (step.instructions ?? step.html_instructions ?? "Continue").replace(/<[^>]*>/g, " ").replace(/&nbsp;/g, " ").replace(/\s+/g, " ").trim(), meters: step.distance?.value ?? 0, seconds: step.duration?.value ?? 0 }))).filter((step) => step.instruction); }
