import { bigint, double, int, json, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });

export const evacuationCenters = mysqlTable("evacuation_centers", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 180 }).notNull(), barangay: varchar("barangay", { length: 180 }).notNull(), latitude: double("latitude").notNull(), longitude: double("longitude").notNull(), capacity: int("capacity").notNull(), availableSlots: int("availableSlots").notNull(), operationalStatus: mysqlEnum("operationalStatus", ["open", "limited", "full", "closed"]).default("open").notNull(), accessibility: json("accessibility"), contactPhone: varchar("contactPhone", { length: 48 }), contactName: varchar("contactName", { length: 160 }), medicalSupport: varchar("medicalSupport", { length: 180 }), sourceName: varchar("sourceName", { length: 180 }), sourceReference: varchar("sourceReference", { length: 500 }), verificationStatus: mysqlEnum("verificationStatus", ["reference", "verified", "stale", "retired"]).default("reference").notNull(), verifiedBy: int("verifiedBy"), verifiedAt: timestamp("verifiedAt"), freshUntil: timestamp("freshUntil"), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });

/** Immutable audit trail for authorized center publication and status changes. */
export const evacuationCenterAudits = mysqlTable("evacuation_center_audits", { id: int("id").autoincrement().primaryKey(), centerId: int("centerId").notNull(), actorId: int("actorId").notNull(), action: mysqlEnum("action", ["created", "updated", "published", "status_changed", "retired"]).notNull(), sourceName: varchar("sourceName", { length: 180 }), previousState: json("previousState"), nextState: json("nextState").notNull(), note: varchar("note", { length: 600 }), createdAt: timestamp("createdAt").defaultNow().notNull() });

export const incidentReports = mysqlTable("incident_reports", { id: int("id").autoincrement().primaryKey(), clientRequestId: varchar("clientRequestId", { length: 96 }).notNull().unique(), category: mysqlEnum("category", ["flooding", "road_blockage", "structural_damage", "medical_sos", "other"]).notNull(), description: text("description"), latitude: double("latitude"), longitude: double("longitude"), accuracyMeters: double("accuracyMeters"), locationLabel: varchar("locationLabel", { length: 255 }), status: mysqlEnum("status", ["queued", "new", "verified", "assigned", "resolved", "rejected"]).default("queued").notNull(), submittedAt: timestamp("submittedAt").defaultNow().notNull(), receivedAt: timestamp("receivedAt") });

/** Stores object references and provenance only; never evidence bytes. */
export const incidentEvidence = mysqlTable("incident_evidence", { id: int("id").autoincrement().primaryKey(), reportId: int("reportId").notNull(), objectKey: varchar("objectKey", { length: 512 }).notNull().unique(), objectUrl: varchar("objectUrl", { length: 700 }).notNull(), originalFilename: varchar("originalFilename", { length: 255 }).notNull(), mimeType: varchar("mimeType", { length: 80 }).notNull(), byteSize: bigint("byteSize", { mode: "number" }).notNull(), checksum: varchar("checksum", { length: 128 }).notNull(), uploadedAt: timestamp("uploadedAt").defaultNow().notNull() });

/** Resident-reported map incidents are published only with explicit photo/map consent. */
export const mapIncidents = mysqlTable("map_incidents", { id: int("id").autoincrement().primaryKey(), clientRequestId: varchar("clientRequestId", { length: 96 }).notNull().unique(), category: mysqlEnum("category", ["flooding", "road_blockage", "structural_damage", "medical_sos", "other"]).notNull(), barangay: varchar("barangay", { length: 180 }).notNull(), summary: text("summary").notNull(), latitude: double("latitude").notNull(), longitude: double("longitude").notNull(), severity: mysqlEnum("severity", ["advisory", "watch", "warning", "critical"]).default("watch").notNull(), status: mysqlEnum("status", ["submitted", "verified", "rejected", "resolved"]).default("submitted").notNull(), photoObjectKey: varchar("photoObjectKey", { length: 512 }).notNull().unique(), photoObjectUrl: varchar("photoObjectUrl", { length: 700 }).notNull(), photoMimeType: varchar("photoMimeType", { length: 80 }).notNull(), photoByteSize: bigint("photoByteSize", { mode: "number" }).notNull(), photoChecksum: varchar("photoChecksum", { length: 128 }).notNull(), mapConsent: mysqlEnum("mapConsent", ["granted", "withheld"]).default("withheld").notNull(), submittedAt: timestamp("submittedAt").defaultNow().notNull() });

/** Updates entered by authorized LGU operations users are map-published as verified closures. */
export const lguClosureUpdates = mysqlTable("lgu_closure_updates", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 220 }).notNull(), barangay: varchar("barangay", { length: 180 }).notNull(), latitude: double("latitude").notNull(), longitude: double("longitude").notNull(), access: mysqlEnum("access", ["use_caution", "restricted", "closed"]).notNull(), cause: varchar("cause", { length: 320 }).notNull(), severity: mysqlEnum("severity", ["advisory", "watch", "warning", "critical"]).default("warning").notNull(), status: mysqlEnum("status", ["active", "cleared"]).default("active").notNull(), verifiedBy: int("verifiedBy").notNull(), verifiedAt: timestamp("verifiedAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });

export const alerts = mysqlTable("alerts", { id: int("id").autoincrement().primaryKey(), headline: varchar("headline", { length: 200 }).notNull(), body: text("body").notNull(), severity: mysqlEnum("severity", ["advisory", "watch", "warning", "critical"]).default("advisory").notNull(), targetName: varchar("targetName", { length: 200 }).notNull(), targetGeometry: json("targetGeometry"), status: mysqlEnum("status", ["draft", "issued", "cancelled", "expired"]).default("draft").notNull(), issuedBy: int("issuedBy"), issuedAt: timestamp("issuedAt"), expiresAt: timestamp("expiresAt"), createdAt: timestamp("createdAt").defaultNow().notNull() });

/** Durable outbox events for a push/SMS provider or in-app notification consumer. */
export const notificationEvents = mysqlTable("notification_events", { id: int("id").autoincrement().primaryKey(), eventType: mysqlEnum("eventType", ["geo_alert", "family_checkin", "incident_update", "sos_submitted", "sos_escalated", "sos_status_update", "circle_sos"]).notNull(), audienceScope: json("audienceScope").notNull(), payload: json("payload").notNull(), deliveryStatus: mysqlEnum("deliveryStatus", ["queued", "sent", "failed"]).default("queued").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), deliveredAt: timestamp("deliveredAt") });

/** Delivery state is isolated from the event payload to support provider retries and per-recipient audit. */
export const notificationDeliveries = mysqlTable("notification_deliveries", { id: int("id").autoincrement().primaryKey(), eventId: int("eventId").notNull(), recipientRef: varchar("recipientRef", { length: 256 }).notNull(), channel: mysqlEnum("channel", ["in_app", "push"]).default("in_app").notNull(), status: mysqlEnum("status", ["queued", "sent", "failed"]).default("queued").notNull(), attemptCount: int("attemptCount").default(0).notNull(), providerReference: varchar("providerReference", { length: 255 }), createdAt: timestamp("createdAt").defaultNow().notNull(), deliveredAt: timestamp("deliveredAt") });

export const volunteerProfiles = mysqlTable("volunteer_profiles", { id: int("id").autoincrement().primaryKey(), fullName: varchar("fullName", { length: 160 }).notNull(), contactPhone: varchar("contactPhone", { length: 48 }).notNull(), barangay: varchar("barangay", { length: 180 }).notNull(), skills: json("skills").notNull(), availability: varchar("availability", { length: 100 }).notNull(), status: mysqlEnum("status", ["submitted", "verified", "active"]).default("submitted").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });

/** Dispatch-grade SOS cases are intentionally separate from family check-ins and evidence-first incident reports. */
export const sosRequests = mysqlTable("sos_requests", { id: int("id").autoincrement().primaryKey(), clientRequestId: varchar("clientRequestId", { length: 96 }).notNull().unique(), publicReference: varchar("publicReference", { length: 48 }).notNull().unique(), residentUserId: int("residentUserId"), sourceReportId: int("sourceReportId"), category: mysqlEnum("category", ["medical", "rescue_evacuation", "trapped_unsafe", "other"]).notNull(), priority: mysqlEnum("priority", ["high", "critical"]).default("high").notNull(), message: varchar("message", { length: 280 }), locationConsent: mysqlEnum("locationConsent", ["granted", "withheld"]).default("withheld").notNull(), latitude: double("latitude"), longitude: double("longitude"), accuracyMeters: double("accuracyMeters"), status: mysqlEnum("status", ["submitted", "acknowledged", "assigned", "escalated", "resolved", "cancelled"]).default("submitted").notNull(), submittedAt: timestamp("submittedAt").defaultNow().notNull(), acknowledgedAt: timestamp("acknowledgedAt"), assignedAt: timestamp("assignedAt"), resolvedAt: timestamp("resolvedAt") });

/** Assignment history preserves dispatcher ownership changes independently of the SOS record. */
export const sosAssignments = mysqlTable("sos_assignments", { id: int("id").autoincrement().primaryKey(), sosRequestId: int("sosRequestId").notNull(), assigneeType: mysqlEnum("assigneeType", ["lgu", "ngo", "response_team", "other"]).default("lgu").notNull(), assigneeName: varchar("assigneeName", { length: 180 }).notNull(), assignedBy: int("assignedBy").notNull(), assignedAt: timestamp("assignedAt").defaultNow().notNull(), releasedAt: timestamp("releasedAt") });

/** Immutable timeline for every dispatch lifecycle transition and internal coordination note. */
export const sosActions = mysqlTable("sos_actions", { id: int("id").autoincrement().primaryKey(), sosRequestId: int("sosRequestId").notNull(), actionType: mysqlEnum("actionType", ["submitted", "acknowledged", "assigned", "contact_attempted", "escalated", "resolved", "cancelled", "report_promoted"]).notNull(), actorId: int("actorId"), actorRole: varchar("actorRole", { length: 48 }).notNull(), note: varchar("note", { length: 600 }), metadata: json("metadata"), createdAt: timestamp("createdAt").defaultNow().notNull() });

/** Contact attempts are separated from status updates so a failed attempt cannot imply completed dispatch. */
export const sosContactAttempts = mysqlTable("sos_contact_attempts", { id: int("id").autoincrement().primaryKey(), sosRequestId: int("sosRequestId").notNull(), channel: mysqlEnum("channel", ["in_app", "push", "phone", "radio", "other"]).notNull(), recipientRef: varchar("recipientRef", { length: 256 }).notNull(), outcome: mysqlEnum("outcome", ["queued", "reached", "failed", "no_answer"]).default("queued").notNull(), attemptedAt: timestamp("attemptedAt").defaultNow().notNull() });

/** Invite-only trusted circles. Membership is required before a resident can view another member's emergency state. */
export const emergencyCircles = mysqlTable("emergency_circles", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull(), inviteCode: varchar("inviteCode", { length: 32 }).notNull().unique(), createdBy: int("createdBy").notNull(), active: mysqlEnum("active", ["active", "archived"]).default("active").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });

/** Each member controls their own status and whether fresh location may be visible to the circle. */
export const emergencyCircleMemberships = mysqlTable("emergency_circle_memberships", { id: int("id").autoincrement().primaryKey(), circleId: int("circleId").notNull(), userId: int("userId").notNull(), displayName: varchar("displayName", { length: 160 }).notNull(), role: mysqlEnum("role", ["owner", "member"]).default("member").notNull(), approvalStatus: mysqlEnum("approvalStatus", ["pending", "approved", "rejected"]).default("pending").notNull(), safetyStatus: mysqlEnum("safetyStatus", ["unknown", "safe", "needs_help"]).default("unknown").notNull(), sharingState: mysqlEnum("sharingState", ["stopped", "sharing"]).default("stopped").notNull(), joinedAt: timestamp("joinedAt").defaultNow().notNull(), approvedAt: timestamp("approvedAt"), lastStatusAt: timestamp("lastStatusAt").defaultNow().notNull(), sharingEndsAt: timestamp("sharingEndsAt") });

/** On-demand location pings expire from visible snapshots; no continuous/background tracking is implied. */
export const emergencyCircleLocationPings = mysqlTable("emergency_circle_location_pings", { id: int("id").autoincrement().primaryKey(), membershipId: int("membershipId").notNull(), latitude: double("latitude").notNull(), longitude: double("longitude").notNull(), accuracyMeters: double("accuracyMeters"), capturedAt: timestamp("capturedAt").defaultNow().notNull(), expiresAt: timestamp("expiresAt").notNull() });

/** Durable circle-only SOS notices. Recipients are limited to other approved members; this is not an LGU dispatch channel. */
export const emergencyCircleSosAlerts = mysqlTable("emergency_circle_sos_alerts", { id: int("id").autoincrement().primaryKey(), circleId: int("circleId").notNull(), initiatorMembershipId: int("initiatorMembershipId").notNull(), message: varchar("message", { length: 280 }), notificationEventId: int("notificationEventId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), expiresAt: timestamp("expiresAt").notNull() });

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type IncidentReport = typeof incidentReports.$inferSelect;
