import { desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { alerts, emergencyCircleLocationPings, emergencyCircleMemberships, emergencyCircles, emergencyCircleSosAlerts, evacuationCenterAudits, evacuationCenters, incidentEvidence, incidentReports, InsertUser, lguClosureUpdates, mapIncidents, notificationDeliveries, notificationEvents, sosActions, sosAssignments, sosContactAttempts, sosRequests, users, volunteerProfiles } from "../drizzle/schema";
import { listCrisisMapFeatures as listCatalogCrisisMapFeatures, pilotCenters, type CrisisMapLayer, type CrisisMapSeverity } from "./drrm.catalog";
import type { ActiveClosure } from "./safe-route";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); } } return _db; }

export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId, name: user.name ?? null, email: user.email ?? null, loginMethod: user.loginMethod ?? null, lastSignedIn: new Date(), role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user") }; await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name, email: values.email, loginMethod: values.loginMethod, role: values.role, lastSignedIn: values.lastSignedIn } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(users).where(eq(users.openId, openId)).limit(1))[0]; }

type CenterVerificationStatus = "reference" | "verified" | "stale" | "retired";
type CenterOperationalInput = { id: number; availableSlots: number; operationalStatus: "open" | "limited" | "full" | "closed"; contactPhone?: string | null; contactName?: string | null; medicalSupport?: string | null; accessibility?: Record<string, unknown> | null; sourceName: string; sourceReference?: string | null; verificationStatus: CenterVerificationStatus; freshUntil?: Date | null; note?: string | null; actorId: number };
function normalizeCenterTrust<T extends Record<string, unknown>>(center: T) { const trust = center as T & { verificationStatus?: CenterVerificationStatus | null; freshUntil?: Date | null; sourceName?: string | null; sourceReference?: string | null; source?: string | null }; const expired = trust.verificationStatus === "verified" && trust.freshUntil && trust.freshUntil.getTime() < Date.now(); const verificationStatus = expired ? "stale" : trust.verificationStatus ?? "reference"; return { ...center, verificationStatus, sourceName: trust.sourceName ?? trust.source ?? "LGU confirmation required", sourceReference: trust.sourceReference ?? null, freshUntil: trust.freshUntil ?? null, isCurrent: verificationStatus === "verified" }; }
export async function listEvacuationCenters(origin?: { latitude: number; longitude: number }) { const db = await getDb(); const rows = db ? await db.select().from(evacuationCenters).orderBy(desc(evacuationCenters.availableSlots)) : []; const centers = (rows.length ? rows : pilotCenters).map((center) => normalizeCenterTrust(center)); if (!origin) return centers; const radians = (value: number) => value * Math.PI / 180; const distanceKm = (latitude: number, longitude: number) => { const earthKm = 6371; const deltaLat = radians(latitude - origin.latitude); const deltaLon = radians(longitude - origin.longitude); const a = Math.sin(deltaLat / 2) ** 2 + Math.cos(radians(origin.latitude)) * Math.cos(radians(latitude)) * Math.sin(deltaLon / 2) ** 2; return Math.round(earthKm * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)) * 10) / 10; }; return centers.map((center) => ({ ...center, distanceKm: distanceKm(center.latitude, center.longitude) })).sort((a, b) => a.distanceKm - b.distanceKm); }
export async function listCrisisMapFeatures(input: { west: number; south: number; east: number; north: number; layers: CrisisMapLayer[]; severities?: CrisisMapSeverity[] }) {
  const catalog = listCatalogCrisisMapFeatures(input);
  const db = await getDb();
  if (!db) return catalog;
  const [closures, incidents] = await Promise.all([db.select().from(lguClosureUpdates), db.select().from(mapIncidents)]);
  const dynamic = [
    ...closures.filter((closure) => closure.status === "active").map((closure) => ({ id: `lgu-closure-${closure.id}`, layer: "roadClosures" as const, latitude: closure.latitude, longitude: closure.longitude, severity: closure.severity, status: "active" as const, updatedAt: closure.updatedAt.toISOString(), properties: { name: closure.name, barangay: closure.barangay, access: closure.access === "use_caution" ? "Use caution" : closure.access === "restricted" ? "Restricted" : "Closed", cause: closure.cause, source: "LGU-verified closure update", lguVerified: true } })),
    ...incidents.filter((incident) => incident.mapConsent === "granted" && incident.status !== "rejected" && incident.status !== "resolved").map((incident) => ({ id: `resident-incident-${incident.id}`, layer: "incidents" as const, latitude: incident.latitude, longitude: incident.longitude, severity: incident.severity, status: "active" as const, updatedAt: incident.submittedAt.toISOString(), properties: { name: `${incident.category.replaceAll("_", " ")} resident report`, barangay: incident.barangay, category: incident.category.replaceAll("_", " "), summary: incident.summary, source: incident.status === "verified" ? "LGU-verified resident evidence" : "Resident-submitted photo evidence", photoUrl: incident.photoObjectUrl, photoMimeType: incident.photoMimeType, verificationStatus: incident.status, referenceOnly: false } })),
  ];
  const severitySensitive = new Set<CrisisMapLayer>(["weather", "flood", "faultLines", "evacuationCenters", "roadClosures", "incidents"]);
  const allowed = input.severities ?? ["advisory", "watch", "warning", "critical"];
  return [...catalog, ...dynamic].filter((feature) => input.layers.includes(feature.layer) && feature.longitude >= input.west && feature.longitude <= input.east && feature.latitude >= input.south && feature.latitude <= input.north && (!severitySensitive.has(feature.layer) || (feature.severity !== undefined && allowed.includes(feature.severity))));
}
export async function createMapIncident(input: { clientRequestId: string; category: "flooding" | "road_blockage" | "structural_damage" | "medical_sos" | "other"; barangay: string; summary: string; latitude: number; longitude: number; severity: "advisory" | "watch" | "warning" | "critical"; mapConsent: "granted" | "withheld"; photo: { objectKey: string; objectUrl: string; mimeType: string; byteSize: number; checksum: string } }) { const db = await getDb(); if (!db) throw new Error("Incident map service is temporarily unavailable"); const existing = (await db.select().from(mapIncidents).where(eq(mapIncidents.clientRequestId, input.clientRequestId)).limit(1))[0]; if (existing) return existing; const result = await db.insert(mapIncidents).values({ clientRequestId: input.clientRequestId, category: input.category, barangay: input.barangay, summary: input.summary, latitude: input.latitude, longitude: input.longitude, severity: input.severity, status: "submitted", mapConsent: input.mapConsent, photoObjectKey: input.photo.objectKey, photoObjectUrl: input.photo.objectUrl, photoMimeType: input.photo.mimeType, photoByteSize: input.photo.byteSize, photoChecksum: input.photo.checksum }); return { id: Number(result[0].insertId), status: "submitted" as const }; }
export async function publishVerifiedClosure(input: { name: string; barangay: string; latitude: number; longitude: number; access: "use_caution" | "restricted" | "closed"; cause: string; severity: "advisory" | "watch" | "warning" | "critical"; verifiedBy: number }) { const db = await getDb(); if (!db) throw new Error("Closure update service is temporarily unavailable"); const result = await db.insert(lguClosureUpdates).values({ ...input, status: "active" }); return { id: Number(result[0].insertId), status: "active" as const }; }
export async function listVerifiedActiveClosures(): Promise<ActiveClosure[]> { const db = await getDb(); if (!db) return []; const closures = await db.select().from(lguClosureUpdates); return closures.filter((closure) => closure.status === "active").map((closure) => ({ id: `lgu-closure-${closure.id}`, latitude: closure.latitude, longitude: closure.longitude, name: closure.name, barangay: closure.barangay, severity: closure.severity })); }
export async function publishEvacuationCenter(input: CenterOperationalInput) { const db = await getDb(); if (!db) throw new Error("Center status service is temporarily unavailable"); const existing = (await db.select().from(evacuationCenters).where(eq(evacuationCenters.id, input.id)).limit(1))[0]; const values = { availableSlots: input.availableSlots, operationalStatus: input.operationalStatus, contactPhone: input.contactPhone ?? null, contactName: input.contactName ?? null, medicalSupport: input.medicalSupport ?? null, accessibility: input.accessibility ?? null, sourceName: input.sourceName, sourceReference: input.sourceReference ?? null, verificationStatus: input.verificationStatus, verifiedBy: input.verificationStatus === "verified" ? input.actorId : null, verifiedAt: input.verificationStatus === "verified" ? new Date() : null, freshUntil: input.freshUntil ?? null };
  if (existing) { await db.update(evacuationCenters).set(values).where(eq(evacuationCenters.id, input.id)); const next = { ...existing, ...values }; await db.insert(evacuationCenterAudits).values({ centerId: input.id, actorId: input.actorId, action: input.verificationStatus === "verified" ? "published" : "updated", sourceName: input.sourceName, previousState: existing, nextState: next, note: input.note ?? null }); return normalizeCenterTrust(next); }
  const catalog = pilotCenters.find((center) => center.id === input.id); if (!catalog) throw new Error("Evacuation center not found"); const created = { ...catalog, ...values }; await db.insert(evacuationCenters).values(created); await db.insert(evacuationCenterAudits).values({ centerId: input.id, actorId: input.actorId, action: input.verificationStatus === "verified" ? "published" : "created", sourceName: input.sourceName, previousState: null, nextState: created, note: input.note ?? null }); return normalizeCenterTrust(created); }
export async function updateEvacuationCenterStatus(input: { id: number; availableSlots: number; operationalStatus: "open" | "limited" | "full" | "closed"; actorId: number }) { const db = await getDb(); if (!db) throw new Error("Center status service is temporarily unavailable"); const existing = (await db.select().from(evacuationCenters).where(eq(evacuationCenters.id, input.id)).limit(1))[0]; if (existing) { const values = { availableSlots: input.availableSlots, operationalStatus: input.operationalStatus }; await db.update(evacuationCenters).set(values).where(eq(evacuationCenters.id, input.id)); const next = { ...existing, ...values }; await db.insert(evacuationCenterAudits).values({ centerId: input.id, actorId: input.actorId, action: "status_changed", sourceName: existing.sourceName, previousState: existing, nextState: next, note: "Operational availability update" }); return normalizeCenterTrust(next); } const catalog = pilotCenters.find((center) => center.id === input.id); if (!catalog) throw new Error("Evacuation center not found"); const created = { ...catalog, availableSlots: input.availableSlots, operationalStatus: input.operationalStatus, verificationStatus: "reference" as const }; await db.insert(evacuationCenters).values(created); await db.insert(evacuationCenterAudits).values({ centerId: input.id, actorId: input.actorId, action: "status_changed", sourceName: catalog.source, previousState: null, nextState: created, note: "Operational availability update" }); return normalizeCenterTrust(created); }
export async function listEvacuationCenterAudits(centerId: number) { const db = await getDb(); if (!db) return []; return db.select().from(evacuationCenterAudits).where(eq(evacuationCenterAudits.centerId, centerId)).orderBy(desc(evacuationCenterAudits.createdAt)).limit(20); }

export async function getReportByClientRequestId(clientRequestId: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(incidentReports).where(eq(incidentReports.clientRequestId, clientRequestId)).limit(1))[0]; }
export async function createIncidentWithEvidence(input: { clientRequestId: string; category: "flooding" | "road_blockage" | "structural_damage" | "medical_sos" | "other"; description?: string; latitude?: number; longitude?: number; accuracyMeters?: number; locationLabel?: string; evidence: { objectKey: string; objectUrl: string; originalFilename: string; mimeType: string; byteSize: number; checksum: string } }) { const db = await getDb(); if (!db) throw new Error("Emergency report service is temporarily unavailable"); const existing = await getReportByClientRequestId(input.clientRequestId); if (existing) return existing; const inserted = await db.insert(incidentReports).values({ clientRequestId: input.clientRequestId, category: input.category, description: input.description ?? null, latitude: input.latitude ?? null, longitude: input.longitude ?? null, accuracyMeters: input.accuracyMeters ?? null, locationLabel: input.locationLabel ?? null, status: "new", receivedAt: new Date() }); const reportId = Number(inserted[0].insertId); await db.insert(incidentEvidence).values({ reportId, ...input.evidence }); return { id: reportId, clientRequestId: input.clientRequestId, status: "new" as const }; }
export async function listRecentReports() { const db = await getDb(); if (!db) return []; return db.select().from(incidentReports).orderBy(desc(incidentReports.submittedAt)).limit(25); }

type SosCategory = "medical" | "rescue_evacuation" | "trapped_unsafe" | "other";
type SosStatus = "submitted" | "acknowledged" | "assigned" | "escalated" | "resolved" | "cancelled";
type SosInput = { clientRequestId: string; category: SosCategory; priority: "high" | "critical"; message?: string; locationConsent: "granted" | "withheld"; latitude?: number; longitude?: number; accuracyMeters?: number; residentUserId?: number };
function sosReference(clientRequestId: string) { return `SOS-${clientRequestId.replaceAll("-", "").slice(0, 8).toUpperCase()}`; }
async function createSosEvent(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, eventType: "sos_submitted" | "sos_escalated" | "sos_status_update", sosId: number, publicReference: string, status: SosStatus) { const event = await db.insert(notificationEvents).values({ eventType, audienceScope: { recipient: "command_center" }, payload: { sosId, publicReference, status }, deliveryStatus: "queued" }); const eventId = Number(event[0].insertId); await queueDelivery(db, eventId, "command-center:balangiga"); return eventId; }
export async function createSosRequest(input: SosInput) { const db = await getDb(); if (!db) throw new Error("SOS service is temporarily unavailable"); const existing = (await db.select().from(sosRequests).where(eq(sosRequests.clientRequestId, input.clientRequestId)).limit(1))[0]; if (existing) return { id: existing.id, publicReference: existing.publicReference, status: existing.status, idempotent: true };
  const publicReference = sosReference(input.clientRequestId); const result = await db.insert(sosRequests).values({ clientRequestId: input.clientRequestId, publicReference, residentUserId: input.residentUserId ?? null, category: input.category, priority: input.priority, message: input.message ?? null, locationConsent: input.locationConsent, latitude: input.locationConsent === "granted" ? input.latitude ?? null : null, longitude: input.locationConsent === "granted" ? input.longitude ?? null : null, accuracyMeters: input.locationConsent === "granted" ? input.accuracyMeters ?? null : null, status: "submitted" }); const id = Number(result[0].insertId); await db.insert(sosActions).values({ sosRequestId: id, actionType: "submitted", actorId: input.residentUserId ?? null, actorRole: "resident", note: null, metadata: { locationConsent: input.locationConsent } }); const eventId = await createSosEvent(db, "sos_submitted", id, publicReference, "submitted"); return { id, publicReference, status: "submitted" as const, eventId, idempotent: false }; }
export async function getSosStatus(publicReference: string) { const db = await getDb(); if (!db) return undefined; const sos = (await db.select().from(sosRequests).where(eq(sosRequests.publicReference, publicReference)).limit(1))[0]; if (!sos) return undefined; return { publicReference: sos.publicReference, status: sos.status, submittedAt: sos.submittedAt, acknowledgedAt: sos.acknowledgedAt, assignedAt: sos.assignedAt, resolvedAt: sos.resolvedAt }; }
export async function listCommandCenterFeed() { const db = await getDb(); if (!db) return []; const [sos, reports] = await Promise.all([db.select().from(sosRequests).orderBy(desc(sosRequests.submittedAt)).limit(50), db.select().from(incidentReports).orderBy(desc(incidentReports.submittedAt)).limit(50)]); const sosRows = sos.filter((item) => item.status !== "resolved" && item.status !== "cancelled").map((item) => ({ feedId: `sos-${item.id}`, sourceType: "sos" as const, sourceId: item.id, publicReference: item.publicReference, priority: item.priority, status: item.status, category: item.category, summary: item.message ?? "Urgent help request", latitude: item.latitude, longitude: item.longitude, accuracyMeters: item.accuracyMeters, submittedAt: item.submittedAt, acknowledgedAt: item.acknowledgedAt, assignedAt: item.assignedAt })); const reportRows = reports.filter((item) => item.status !== "resolved" && item.status !== "rejected").map((item) => ({ feedId: `report-${item.id}`, sourceType: "incident_report" as const, sourceId: item.id, publicReference: `IR-${item.id}`, priority: item.category === "medical_sos" ? "high" as const : "normal" as const, status: item.status, category: item.category, summary: item.description ?? "Resident incident report", latitude: item.latitude, longitude: item.longitude, accuracyMeters: item.accuracyMeters, submittedAt: item.submittedAt, acknowledgedAt: null, assignedAt: item.status === "assigned" ? item.submittedAt : null })); return [...sosRows, ...reportRows].sort((a, b) => { const score = (item: typeof a) => item.sourceType === "sos" && item.status === "submitted" ? 0 : item.priority === "critical" ? 1 : item.priority === "high" ? 2 : 3; return score(a) - score(b) || b.submittedAt.getTime() - a.submittedAt.getTime(); }); }
async function getSosOrThrow(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, id: number) { const sos = (await db.select().from(sosRequests).where(eq(sosRequests.id, id)).limit(1))[0]; if (!sos) throw new Error("SOS request not found"); return sos; }
export async function acknowledgeSos(input: { id: number; actorId: number }) { const db = await getDb(); if (!db) throw new Error("SOS service is temporarily unavailable"); const sos = await getSosOrThrow(db, input.id); if (sos.status !== "submitted" && sos.status !== "escalated") return sos; const now = new Date(); await db.update(sosRequests).set({ status: "acknowledged", acknowledgedAt: now }).where(eq(sosRequests.id, input.id)); await db.insert(sosActions).values({ sosRequestId: input.id, actionType: "acknowledged", actorId: input.actorId, actorRole: "dispatcher", note: null, metadata: null }); await createSosEvent(db, "sos_status_update", input.id, sos.publicReference, "acknowledged"); return { ...sos, status: "acknowledged" as const, acknowledgedAt: now }; }
export async function assignSos(input: { id: number; assigneeType: "lgu" | "ngo" | "response_team" | "other"; assigneeName: string; actorId: number; note?: string }) { const db = await getDb(); if (!db) throw new Error("SOS service is temporarily unavailable"); const sos = await getSosOrThrow(db, input.id); const now = new Date(); await db.insert(sosAssignments).values({ sosRequestId: input.id, assigneeType: input.assigneeType, assigneeName: input.assigneeName, assignedBy: input.actorId }); await db.update(sosRequests).set({ status: "assigned", assignedAt: now }).where(eq(sosRequests.id, input.id)); await db.insert(sosActions).values({ sosRequestId: input.id, actionType: "assigned", actorId: input.actorId, actorRole: "dispatcher", note: input.note ?? null, metadata: { assigneeType: input.assigneeType, assigneeName: input.assigneeName } }); await createSosEvent(db, "sos_status_update", input.id, sos.publicReference, "assigned"); return { ...sos, status: "assigned" as const, assignedAt: now, assigneeName: input.assigneeName }; }
export async function resolveSos(input: { id: number; actorId: number; note: string }) { const db = await getDb(); if (!db) throw new Error("SOS service is temporarily unavailable"); const sos = await getSosOrThrow(db, input.id); const now = new Date(); await db.update(sosRequests).set({ status: "resolved", resolvedAt: now }).where(eq(sosRequests.id, input.id)); await db.insert(sosActions).values({ sosRequestId: input.id, actionType: "resolved", actorId: input.actorId, actorRole: "dispatcher", note: input.note, metadata: null }); await createSosEvent(db, "sos_status_update", input.id, sos.publicReference, "resolved"); return { ...sos, status: "resolved" as const, resolvedAt: now }; }
export async function escalateSos(input: { id: number; actorId: number; note: string }) { const db = await getDb(); if (!db) throw new Error("SOS service is temporarily unavailable"); const sos = await getSosOrThrow(db, input.id); await db.update(sosRequests).set({ status: "escalated" }).where(eq(sosRequests.id, input.id)); await db.insert(sosActions).values({ sosRequestId: input.id, actionType: "escalated", actorId: input.actorId, actorRole: "dispatcher", note: input.note, metadata: { externalDispatchConfigured: false } }); await createSosEvent(db, "sos_escalated", input.id, sos.publicReference, "escalated"); return { ...sos, status: "escalated" as const }; }
export async function listSosActions(sosRequestId: number) { const db = await getDb(); if (!db) return []; return db.select().from(sosActions).where(eq(sosActions.sosRequestId, sosRequestId)).orderBy(desc(sosActions.createdAt)); }
export async function logSosContactAttempt(input: { id: number; actorId: number; channel: "in_app" | "push" | "phone" | "radio" | "other"; recipientRef: string; outcome: "queued" | "reached" | "failed" | "no_answer" }) { const db = await getDb(); if (!db) throw new Error("SOS service is temporarily unavailable"); await getSosOrThrow(db, input.id); await db.insert(sosContactAttempts).values({ sosRequestId: input.id, channel: input.channel, recipientRef: input.recipientRef, outcome: input.outcome }); await db.insert(sosActions).values({ sosRequestId: input.id, actionType: "contact_attempted", actorId: input.actorId, actorRole: "dispatcher", note: null, metadata: { channel: input.channel, recipientRef: input.recipientRef, outcome: input.outcome } }); return { status: "logged" as const }; }

async function queueDelivery(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, eventId: number, recipientRef: string) { await db.insert(notificationDeliveries).values({ eventId, recipientRef, channel: "in_app", status: "queued", attemptCount: 0 }); }
export async function issueAlert(input: { headline: string; body: string; severity: "advisory" | "watch" | "warning" | "critical"; targetName: string; issuedBy?: number }) { const db = await getDb(); if (!db) throw new Error("Alert service is temporarily unavailable"); const result = await db.insert(alerts).values({ ...input, status: "issued", issuedAt: new Date() }); const alertId = Number(result[0].insertId); const event = await db.insert(notificationEvents).values({ eventType: "geo_alert", audienceScope: { targetName: input.targetName }, payload: { alertId, headline: input.headline, body: input.body, severity: input.severity }, deliveryStatus: "queued" }); const eventId = Number(event[0].insertId); await queueDelivery(db, eventId, `geofence:${input.targetName}`); return { id: alertId, eventId, status: "issued" as const, deliveryStatus: "queued" as const }; }
export async function listActiveAlerts() { const db = await getDb(); if (!db) return []; return db.select().from(alerts).where(eq(alerts.status, "issued")).orderBy(desc(alerts.issuedAt)).limit(20); }
export async function queueFamilyCheckin(input: { status: "safe" | "needs_help"; message?: string; userId?: number }) { const db = await getDb(); if (!db) throw new Error("Check-in service is temporarily unavailable"); const result = await db.insert(notificationEvents).values({ eventType: "family_checkin", audienceScope: { userId: input.userId ?? null, relationship: "family_circle" }, payload: { status: input.status, message: input.message ?? null }, deliveryStatus: "queued" }); const eventId = Number(result[0].insertId); await queueDelivery(db, eventId, `family-circle:${input.userId ?? "anonymous"}`); return { id: eventId, status: "queued" as const, recipientDeliveryStatus: "queued" as const }; }
export async function createVolunteerProfile(input: { fullName: string; contactPhone: string; barangay: string; skills: string[]; availability: string }) { const db = await getDb(); if (!db) throw new Error("Volunteer service is temporarily unavailable"); const result = await db.insert(volunteerProfiles).values({ ...input, status: "submitted" }); return { id: Number(result[0].insertId), status: "submitted" as const }; }

type CircleStatus = "unknown" | "safe" | "needs_help";
type CircleApprovalStatus = "pending" | "approved" | "rejected";
function circleInviteCode() { return `EC-${crypto.randomUUID().replaceAll("-", "").slice(0, 10).toUpperCase()}`; }
async function membershipFor(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, circleId: number, userId: number) { return (await db.select().from(emergencyCircleMemberships).where(eq(emergencyCircleMemberships.circleId, circleId))).find((membership) => membership.userId === userId); }
function requireApprovedMembership(membership: Awaited<ReturnType<typeof membershipFor>>) { if (!membership || membership.approvalStatus !== "approved") throw new Error("Your circle membership is awaiting owner approval"); return membership; }
export async function createEmergencyCircle(input: { name: string; userId: number; displayName: string }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const inviteCode = circleInviteCode(); const now = new Date(); const result = await db.insert(emergencyCircles).values({ name: input.name, inviteCode, createdBy: input.userId, active: "active" }); const id = Number(result[0].insertId); await db.insert(emergencyCircleMemberships).values({ circleId: id, userId: input.userId, displayName: input.displayName, role: "owner", approvalStatus: "approved", approvedAt: now, safetyStatus: "unknown", sharingState: "stopped" }); return { id, name: input.name, inviteCode, role: "owner" as const }; }
export async function joinEmergencyCircle(input: { inviteCode: string; userId: number; displayName: string }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const circle = (await db.select().from(emergencyCircles).where(eq(emergencyCircles.inviteCode, input.inviteCode)).limit(1))[0]; if (!circle || circle.active !== "active") throw new Error("Emergency circle invite was not found or is no longer active"); const existing = await membershipFor(db, circle.id, input.userId); if (existing) return { id: circle.id, name: circle.name, approvalStatus: existing.approvalStatus, alreadyRequested: true }; await db.insert(emergencyCircleMemberships).values({ circleId: circle.id, userId: input.userId, displayName: input.displayName, role: "member", approvalStatus: "pending", safetyStatus: "unknown", sharingState: "stopped" }); return { id: circle.id, name: circle.name, approvalStatus: "pending" as const, alreadyRequested: false }; }
export async function reviewEmergencyCircleJoinRequest(input: { circleId: number; ownerUserId: number; membershipId: number; decision: "approve" | "reject" }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const owner = requireApprovedMembership(await membershipFor(db, input.circleId, input.ownerUserId)); if (owner.role !== "owner") throw new Error("Only the circle owner can review join requests"); const request = (await db.select().from(emergencyCircleMemberships).where(eq(emergencyCircleMemberships.id, input.membershipId)).limit(1))[0]; if (!request || request.circleId !== input.circleId || request.role === "owner" || request.approvalStatus !== "pending") throw new Error("Join request was not found or has already been reviewed"); const approvalStatus: CircleApprovalStatus = input.decision === "approve" ? "approved" : "rejected"; const reviewedAt = new Date(); await db.update(emergencyCircleMemberships).set({ approvalStatus, approvedAt: approvalStatus === "approved" ? reviewedAt : null }).where(eq(emergencyCircleMemberships.id, request.id)); return { membershipId: request.id, displayName: request.displayName, approvalStatus, reviewedAt }; }
export async function rotateEmergencyCircleInviteCode(input: { circleId: number; ownerUserId: number }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const owner = requireApprovedMembership(await membershipFor(db, input.circleId, input.ownerUserId)); if (owner.role !== "owner") throw new Error("Only the circle owner can rotate this invite code"); const circle = (await db.select().from(emergencyCircles).where(eq(emergencyCircles.id, input.circleId)).limit(1))[0]; if (!circle || circle.active !== "active") throw new Error("Emergency circle was not found or is no longer active"); const inviteCode = circleInviteCode(); await db.update(emergencyCircles).set({ inviteCode }).where(eq(emergencyCircles.id, input.circleId)); return { inviteCode, rotatedAt: new Date() }; }
export async function removeEmergencyCircleMember(input: { circleId: number; ownerUserId: number; membershipId: number }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const owner = requireApprovedMembership(await membershipFor(db, input.circleId, input.ownerUserId)); if (owner.role !== "owner") throw new Error("Only the circle owner can remove members"); const member = (await db.select().from(emergencyCircleMemberships).where(eq(emergencyCircleMemberships.id, input.membershipId)).limit(1))[0]; if (!member || member.circleId !== input.circleId || member.role === "owner" || member.approvalStatus !== "approved") throw new Error("Only approved non-owner members can be removed"); await db.delete(emergencyCircleLocationPings).where(eq(emergencyCircleLocationPings.membershipId, member.id)); await db.delete(emergencyCircleMemberships).where(eq(emergencyCircleMemberships.id, member.id)); return { membershipId: member.id, displayName: member.displayName, removedAt: new Date() }; }
export async function listMyEmergencyCircles(userId: number) { const db = await getDb(); if (!db) return []; const memberships = (await db.select().from(emergencyCircleMemberships)).filter((membership) => membership.userId === userId); const circles = await db.select().from(emergencyCircles); return memberships.map((membership) => { const circle = circles.find((item) => item.id === membership.circleId); return circle ? { id: circle.id, name: circle.name, role: membership.role, approvalStatus: membership.approvalStatus, safetyStatus: membership.safetyStatus, sharingState: membership.sharingState, sharingEndsAt: membership.sharingEndsAt } : null; }).filter((circle): circle is NonNullable<typeof circle> => Boolean(circle)); }
export async function updateEmergencyCircleStatus(input: { circleId: number; userId: number; status: CircleStatus }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const membership = requireApprovedMembership(await membershipFor(db, input.circleId, input.userId)); const now = new Date(); await db.update(emergencyCircleMemberships).set({ safetyStatus: input.status, lastStatusAt: now }).where(eq(emergencyCircleMemberships.id, membership.id)); return { status: input.status, lastStatusAt: now }; }
export async function shareEmergencyCircleLocation(input: { circleId: number; userId: number; latitude: number; longitude: number; accuracyMeters?: number }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const membership = requireApprovedMembership(await membershipFor(db, input.circleId, input.userId)); const now = new Date(); const expiresAt = new Date(now.getTime() + 30 * 60 * 1000); await db.update(emergencyCircleMemberships).set({ sharingState: "sharing", sharingEndsAt: expiresAt }).where(eq(emergencyCircleMemberships.id, membership.id)); await db.insert(emergencyCircleLocationPings).values({ membershipId: membership.id, latitude: input.latitude, longitude: input.longitude, accuracyMeters: input.accuracyMeters ?? null, expiresAt }); return { sharingState: "sharing" as const, expiresAt }; }
export async function stopEmergencyCircleLocation(input: { circleId: number; userId: number }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const membership = requireApprovedMembership(await membershipFor(db, input.circleId, input.userId)); await db.update(emergencyCircleMemberships).set({ sharingState: "stopped", sharingEndsAt: new Date() }).where(eq(emergencyCircleMemberships.id, membership.id)); return { sharingState: "stopped" as const }; }
export async function sendEmergencyCircleSos(input: { circleId: number; userId: number; message?: string }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const initiator = requireApprovedMembership(await membershipFor(db, input.circleId, input.userId)); const circle = (await db.select().from(emergencyCircles).where(eq(emergencyCircles.id, input.circleId)).limit(1))[0]; if (!circle || circle.active !== "active") throw new Error("Emergency circle was not found or is no longer active"); const recipients = (await db.select().from(emergencyCircleMemberships).where(eq(emergencyCircleMemberships.circleId, input.circleId))).filter((member) => member.approvalStatus === "approved" && member.id !== initiator.id); const now = new Date(); const expiresAt = new Date(now.getTime() + 6 * 60 * 60 * 1000); await db.update(emergencyCircleMemberships).set({ safetyStatus: "needs_help", lastStatusAt: now }).where(eq(emergencyCircleMemberships.id, initiator.id)); const event = await db.insert(notificationEvents).values({ eventType: "circle_sos", audienceScope: { circleId: input.circleId, recipientMembershipIds: recipients.map((member) => member.id) }, payload: { circleId: input.circleId, circleName: circle.name, initiatedBy: initiator.displayName, message: input.message ?? null, expiresAt }, deliveryStatus: "queued" }); const eventId = Number(event[0].insertId); const alert = await db.insert(emergencyCircleSosAlerts).values({ circleId: input.circleId, initiatorMembershipId: initiator.id, message: input.message ?? null, notificationEventId: eventId, expiresAt }); const alertId = Number(alert[0].insertId); await Promise.all(recipients.map((recipient) => queueDelivery(db, eventId, `user:${recipient.userId}`))); return { id: alertId, eventId, recipientCount: recipients.length, createdAt: now, expiresAt }; }
export async function listMyEmergencyCircleSosAlerts(userId: number) { const db = await getDb(); if (!db) return []; const myMemberships = (await db.select().from(emergencyCircleMemberships)).filter((membership) => membership.userId === userId && membership.approvalStatus === "approved"); const byCircle = new Map(myMemberships.map((membership) => [membership.circleId, membership])); if (!byCircle.size) return []; const now = new Date(); const [circles, alerts, memberships] = await Promise.all([db.select().from(emergencyCircles), db.select().from(emergencyCircleSosAlerts), db.select().from(emergencyCircleMemberships)]); return alerts.filter((alert) => alert.expiresAt.getTime() > now.getTime() && byCircle.has(alert.circleId) && byCircle.get(alert.circleId)?.id !== alert.initiatorMembershipId).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()).map((alert) => { const initiator = memberships.find((membership) => membership.id === alert.initiatorMembershipId); const circle = circles.find((item) => item.id === alert.circleId); return { id: alert.id, circleId: alert.circleId, circleName: circle?.name ?? "Emergency circle", initiatedBy: initiator?.displayName ?? "Circle member", message: alert.message, createdAt: alert.createdAt, expiresAt: alert.expiresAt }; }); }
export async function getEmergencyCircleSnapshot(input: { circleId: number; userId: number }) { const db = await getDb(); if (!db) throw new Error("Emergency circle service is temporarily unavailable"); const viewer = requireApprovedMembership(await membershipFor(db, input.circleId, input.userId)); const circle = (await db.select().from(emergencyCircles).where(eq(emergencyCircles.id, input.circleId)).limit(1))[0]; if (!circle) throw new Error("Emergency circle not found"); const now = new Date(); const allMemberships = await db.select().from(emergencyCircleMemberships).where(eq(emergencyCircleMemberships.circleId, input.circleId)); const members = allMemberships.filter((member) => member.approvalStatus === "approved"); const pings = await db.select().from(emergencyCircleLocationPings); const visiblePings = pings.filter((ping) => ping.expiresAt.getTime() > now.getTime()); const activeAlerts = (await db.select().from(emergencyCircleSosAlerts).where(eq(emergencyCircleSosAlerts.circleId, input.circleId))).filter((alert) => alert.expiresAt.getTime() > now.getTime()).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime()).slice(0, 10); return { id: circle.id, name: circle.name, inviteCode: viewer.role === "owner" ? circle.inviteCode : null, viewerMembershipId: viewer.id, pendingMembers: viewer.role === "owner" ? allMemberships.filter((member) => member.approvalStatus === "pending").map((member) => ({ id: member.id, displayName: member.displayName, requestedAt: member.joinedAt })) : [], alerts: activeAlerts.map((alert) => { const initiator = members.find((member) => member.id === alert.initiatorMembershipId); return { id: alert.id, initiatedBy: initiator?.displayName ?? "Circle member", message: alert.message, createdAt: alert.createdAt, expiresAt: alert.expiresAt }; }), members: members.map((member) => { const latest = visiblePings.filter((ping) => ping.membershipId === member.id).sort((a, b) => b.capturedAt.getTime() - a.capturedAt.getTime())[0]; const locationVisible = member.sharingState === "sharing" && member.sharingEndsAt && member.sharingEndsAt.getTime() > now.getTime() && latest; return { id: member.id, displayName: member.displayName, role: member.role, safetyStatus: member.safetyStatus, lastStatusAt: member.lastStatusAt, sharingState: locationVisible ? "sharing" as const : "stopped" as const, sharingEndsAt: member.sharingEndsAt, location: locationVisible ? { latitude: latest.latitude, longitude: latest.longitude, accuracyMeters: latest.accuracyMeters, capturedAt: latest.capturedAt, expiresAt: latest.expiresAt } : null }; }) }; }
