export const pilotCenters = [
  { id: 1, name: "Balangiga evacuation roster", barangay: "Balangiga, Eastern Samar", latitude: 11.1086, longitude: 125.3877, capacity: 0, availableSlots: 0, operationalStatus: "limited" as const, accessibility: { wheelchair: false }, contactPhone: "0917 117 0807", source: "reference-pending-verification" as const },
];

export const pilotHazardSnapshot = { severity: "watch" as const, title: "Balangiga coastal weather readiness", body: "Monitor official weather bulletins and local advisories. Confirm safe movement and evacuation arrangements with the Balangiga LGU before travelling.", area: "Balangiga, Eastern Samar and adjacent municipalities", observedAt: "Reference view", sourceLabel: "Balangiga readiness reference" };

export type CrisisMapLayer = "weather" | "flood" | "faultLines" | "evacuationCenters" | "responseTeams" | "roadClosures" | "incidents";
export type CrisisMapSeverity = "advisory" | "watch" | "warning" | "critical";
export type CrisisMapFeature = { id: string; layer: CrisisMapLayer; latitude: number; longitude: number; severity?: CrisisMapSeverity; status?: "open" | "limited" | "full" | "active"; updatedAt: string; properties: Record<string, string | number | boolean> };

export const balangigaCrisisFeatures: CrisisMapFeature[] = [
  { id: "pagasa-eastern-samar-01", layer: "weather", latitude: 11.1086, longitude: 125.3877, severity: "watch", updatedAt: "Reference forecast context", properties: { source: "PAGASA advisory context", title: "Eastern Samar coastal rainfall watch", validity: "reference" } },
  { id: "flood-balangiga-01", layer: "flood", latitude: 11.1086, longitude: 125.3877, severity: "warning", updatedAt: "LGU reference snapshot", properties: { title: "Balangiga coastal and river flood susceptibility", source: "LGU confirmation required", lguConfirmed: false, coverage: "Balangiga" } },
  { id: "flood-lawaan-01", layer: "flood", latitude: 11.185, longitude: 125.286, severity: "watch", updatedAt: "Provincial reference snapshot", properties: { title: "Lawaan low-lying area reference", source: "Provincial reference", lguConfirmed: false, coverage: "Lawaan" } },
  { id: "fault-eastern-samar-01", layer: "faultLines", latitude: 11.224, longitude: 125.514, severity: "advisory", updatedAt: "Reference view", properties: { title: "Eastern Samar ground-shaking reference", source: "Confirm current PHIVOLCS advisories" } },
  { id: "center-balangiga-01", layer: "evacuationCenters", latitude: 11.1086, longitude: 125.3877, severity: "warning", status: "limited", updatedAt: "Reference pending LGU verification", properties: { name: "Balangiga evacuation roster — verify with LGU", capacity: 0, availableSlots: 0, accessibility: false, referenceOnly: true } },
  { id: "center-lawaan-01", layer: "evacuationCenters", latitude: 11.185, longitude: 125.286, severity: "watch", status: "limited", updatedAt: "Reference pending LGU verification", properties: { name: "Lawaan evacuation reference — verify with LGU", capacity: 0, availableSlots: 0, accessibility: false, referenceOnly: true } },
  { id: "center-giporlos-01", layer: "evacuationCenters", latitude: 11.12, longitude: 125.45, severity: "advisory", status: "open", updatedAt: "Reference pending LGU verification", properties: { name: "Giporlos evacuation reference — verify with LGU", capacity: 0, availableSlots: 0, accessibility: false, referenceOnly: true } },
  { id: "team-balangiga-placeholder-01", layer: "responseTeams", latitude: 11.1086, longitude: 125.3877, status: "active", updatedAt: "Reference placeholder", properties: { name: "Balangiga response position — placeholder", organization: "Balangiga LGU operations", placeholder: true } },
  { id: "team-eastern-samar-placeholder-02", layer: "responseTeams", latitude: 11.18, longitude: 125.45, status: "active", updatedAt: "Reference placeholder", properties: { name: "Eastern Samar response position — placeholder", organization: "Provincial operations", placeholder: true } },
  { id: "road-balangiga-pob-01", layer: "roadClosures", latitude: 11.108, longitude: 125.381, severity: "warning", status: "active", updatedAt: "Reference pending barangay verification", properties: { name: "Poblacion coastal approach", barangay: "Poblacion, Balangiga", access: "Restricted", cause: "Surface flooding reference", source: "Community report reference — confirm with LGU", referenceOnly: true } },
  { id: "road-lawaan-01", layer: "roadClosures", latitude: 11.184, longitude: 125.29, severity: "watch", status: "active", updatedAt: "Reference pending barangay verification", properties: { name: "Lawaan–Balangiga access reference", barangay: "Lawaan", access: "Use caution", cause: "Low-lying road reference", source: "Community report reference — confirm with LGU", referenceOnly: true } },
  { id: "incident-balangiga-01", layer: "incidents", latitude: 11.111, longitude: 125.395, severity: "warning", status: "active", updatedAt: "Reference pending barangay verification", properties: { name: "Flooding report reference", barangay: "Maybunga, Balangiga", category: "Flooding", summary: "Community-reported standing water reference", source: "Unverified community report", referenceOnly: true } },
  { id: "incident-giporlos-01", layer: "incidents", latitude: 11.123, longitude: 125.454, severity: "watch", status: "active", updatedAt: "Reference pending barangay verification", properties: { name: "Blocked-access report reference", barangay: "Giporlos", category: "Road blockage", summary: "Community-reported access concern reference", source: "Unverified community report", referenceOnly: true } },
];

export function listCrisisMapFeatures(input: { west: number; south: number; east: number; north: number; layers: CrisisMapLayer[]; severities?: CrisisMapSeverity[] }) {
  const severitySensitiveLayers: CrisisMapLayer[] = ["weather", "flood", "faultLines", "evacuationCenters", "roadClosures", "incidents"];
  const severities = input.severities ?? ["advisory", "watch", "warning", "critical"];
  return balangigaCrisisFeatures.filter((feature) => input.layers.includes(feature.layer) && feature.longitude >= input.west && feature.longitude <= input.east && feature.latitude >= input.south && feature.latitude <= input.north && (!severitySensitiveLayers.includes(feature.layer) || (feature.severity !== undefined && severities.includes(feature.severity))));
}
