// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import React from "react";
import EmergencyCircle from "../client/src/pages/EmergencyCircle";

type Circle = { id: number; name: string; role: "owner" | "member"; approvalStatus: "approved" | "pending" | "rejected"; safetyStatus: "unknown"; sharingState: "stopped"; sharingEndsAt: null };
const state = vi.hoisted(() => ({ circles: [] as Circle[], snapshot: undefined as unknown, alerts: [] as unknown[], create: vi.fn(), status: vi.fn(), review: vi.fn(), rotate: vi.fn(), remove: vi.fn(), sendSos: vi.fn(), invalidate: vi.fn(), refetch: vi.fn() }));

vi.mock("../client/src/_core/hooks/useAuth", () => ({ useAuth: () => ({ user: { id: 1, name: "Ari", role: "user" } }) }));
vi.mock("../client/src/lib/trpc", () => ({ trpc: { useUtils: () => ({ circles: { my: { invalidate: state.invalidate }, alerts: { invalidate: state.invalidate } } }), circles: { my: { useQuery: () => ({ data: state.circles }) }, alerts: { useQuery: () => ({ data: state.alerts }) }, snapshot: { useQuery: () => ({ data: state.snapshot, refetch: state.refetch }) }, create: { useMutation: ({ onSuccess }: { onSuccess: (circle: { id: number }) => void }) => ({ mutate: (input: unknown) => { state.create(input); onSuccess({ id: 8 }); }, isPending: false }) }, join: { useMutation: () => ({ mutate: vi.fn(), isPending: false }) }, reviewJoin: { useMutation: ({ onSuccess }: { onSuccess: (result: { approvalStatus: "approved"; displayName: string }) => void }) => ({ mutate: (input: unknown) => { state.review(input); onSuccess({ approvalStatus: "approved", displayName: "Mira" }); }, isPending: false }) }, rotateInvite: { useMutation: ({ onSuccess }: { onSuccess: () => void }) => ({ mutate: (input: unknown) => { state.rotate(input); onSuccess(); }, isPending: false }) }, removeMember: { useMutation: ({ onSuccess }: { onSuccess: (result: { displayName: string }) => void }) => ({ mutate: (input: unknown) => { state.remove(input); onSuccess({ displayName: "Mira" }); }, isPending: false }) }, status: { useMutation: ({ onSuccess }: { onSuccess: () => void }) => ({ mutate: (input: unknown) => { state.status(input); onSuccess(); }, isPending: false }) }, sendSos: { useMutation: ({ onSuccess }: { onSuccess: (result: { recipientCount: number }) => void }) => ({ mutate: (input: unknown) => { state.sendSos(input); onSuccess({ recipientCount: 2 }); }, isPending: false }) }, shareLocation: { useMutation: () => ({ mutate: vi.fn(), isPending: false }) }, stopLocation: { useMutation: () => ({ mutate: vi.fn(), isPending: false }) } } } }));
vi.mock("../client/src/components/drrm/CivilianShell", () => ({ CivilianShell: ({ children }: { children: React.ReactNode }) => <main>{children}</main> }));
vi.mock("../client/src/components/drrm/DrrmPrimitives", () => ({ AppCard: ({ children, className }: { children: React.ReactNode; className?: string }) => <section className={className}>{children}</section>, StatusPill: ({ children }: { children: React.ReactNode }) => <span>{children}</span> }));
vi.mock("../client/src/components/drrm/DrrmDomain", () => ({ DrrmNotice: ({ children }: { children: React.ReactNode }) => <aside>{children}</aside> }));

const approvedCircle: Circle = { id: 8, name: "Family", role: "owner", approvalStatus: "approved", safetyStatus: "unknown", sharingState: "stopped", sharingEndsAt: null };
const ownerSnapshot = { id: 8, name: "Family", inviteCode: "EC-ABC123", viewerMembershipId: 12, pendingMembers: [], alerts: [], members: [{ id: 12, displayName: "Ari", role: "owner", safetyStatus: "unknown", lastStatusAt: new Date(), sharingState: "stopped", sharingEndsAt: null, location: null }] };

beforeEach(() => { state.circles = []; state.snapshot = undefined; state.alerts = []; state.create.mockReset(); state.status.mockReset(); state.review.mockReset(); state.rotate.mockReset(); state.remove.mockReset(); state.sendSos.mockReset(); state.invalidate.mockReset(); state.refetch.mockReset(); vi.spyOn(window, "confirm").mockReturnValue(true); });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

describe("emergency circle resident controls", () => {
  it("creates an invite-only circle with the resident-selected display name", () => { render(<EmergencyCircle/>); fireEvent.change(screen.getByPlaceholderText("Circle name"), { target: { value: "Eastern Samar family" } }); fireEvent.click(screen.getByRole("button", { name: "Create trusted circle" })); expect(state.create).toHaveBeenCalledWith({ name: "Eastern Samar family", displayName: "Ari" }); expect(state.invalidate).toHaveBeenCalled(); });
  it("updates only the signed-in approved member’s safety state from the active circle", () => { state.circles = [approvedCircle]; state.snapshot = ownerSnapshot; render(<EmergencyCircle/>); fireEvent.click(screen.getByRole("button", { name: /I’m safe/i })); expect(state.status).toHaveBeenCalledWith({ circleId: 8, status: "safe" }); });
  it("gives the owner a review control for a pending join request", () => { state.circles = [approvedCircle]; state.snapshot = { ...ownerSnapshot, pendingMembers: [{ id: 44, displayName: "Mira", requestedAt: new Date() }] }; render(<EmergencyCircle/>); fireEvent.click(screen.getByRole("button", { name: "Approve" })); expect(state.review).toHaveBeenCalledWith({ circleId: 8, membershipId: 44, decision: "approve" }); });
  it("requires a deliberate confirmation before sending a circle SOS to approved members", () => { state.circles = [approvedCircle]; state.snapshot = ownerSnapshot; render(<EmergencyCircle/>); fireEvent.click(screen.getByRole("button", { name: "Send SOS to circle" })); expect(window.confirm).toHaveBeenCalled(); expect(state.sendSos).toHaveBeenCalledWith({ circleId: 8 }); });
  it("lets the owner rotate an invite code and remove a non-owner member after confirmation", () => { state.circles = [approvedCircle]; state.snapshot = { ...ownerSnapshot, members: [...ownerSnapshot.members, { id: 18, displayName: "Mira", role: "member", safetyStatus: "safe", lastStatusAt: new Date(), sharingState: "stopped", sharingEndsAt: null, location: null }] }; render(<EmergencyCircle/>); fireEvent.click(screen.getByRole("button", { name: "Rotate invite code" })); fireEvent.click(screen.getByRole("button", { name: "Remove Mira from circle" })); expect(state.rotate).toHaveBeenCalledWith({ circleId: 8 }); expect(state.remove).toHaveBeenCalledWith({ circleId: 8, membershipId: 18 }); });
  it("renders a pulsing active SOS card with a manual sound cue control", () => { state.alerts = [{ id: 91, circleName: "Family", initiatedBy: "Mira", message: "Need assistance", createdAt: new Date(), expiresAt: new Date(Date.now() + 60_000) }]; render(<EmergencyCircle/>); expect(screen.getByLabelText("Circle SOS alerts").querySelector(".circle-sos-alert")).not.toBeNull(); expect(screen.getByRole("button", { name: "Play SOS sound" })).toBeTruthy(); });
});
