import { createHash, randomUUID } from "crypto";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { notifyOwner } from "./_core/notification";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { acknowledgeSos, assignSos, createEmergencyCircle, createIncidentWithEvidence, createMapIncident, createSosRequest, createVolunteerProfile, escalateSos, getEmergencyCircleSnapshot, getReportByClientRequestId, getSosStatus, issueAlert, joinEmergencyCircle, listActiveAlerts, listCommandCenterFeed, listCrisisMapFeatures, listEvacuationCenterAudits, listEvacuationCenters, listMyEmergencyCircleSosAlerts, listMyEmergencyCircles, listRecentReports, listSosActions, listVerifiedActiveClosures, logSosContactAttempt, publishEvacuationCenter, publishVerifiedClosure, queueFamilyCheckin, removeEmergencyCircleMember, resolveSos, reviewEmergencyCircleJoinRequest, rotateEmergencyCircleInviteCode, sendEmergencyCircleSos, shareEmergencyCircleLocation, stopEmergencyCircleLocation, updateEmergencyCircleStatus, updateEvacuationCenterStatus } from "./db";
import { pilotHazardSnapshot } from "./drrm.catalog";
import { storagePut } from "./storage";
import { getHybridWeather } from "./weather";
import { aggregateRouteLegs, calculateRoadNetworkSafeRoute } from "./safe-route";
import { makeRequest, type DirectionsResult } from "./_core/map";

const photoSchema = z.object({ dataUrl: z.string().max(15_000_000), filename: z.string().min(1).max(255) });
const reportSchema = z.object({ clientRequestId: z.string().uuid(), category: z.enum(["flooding", "road_blockage", "structural_damage", "medical_sos", "other"]), description: z.string().max(600).optional(), latitude: z.number().gte(-90).lte(90).optional(), longitude: z.number().gte(-180).lte(180).optional(), accuracyMeters: z.number().positive().max(100000).optional(), locationLabel: z.string().max(255).optional(), photo: photoSchema });

export function parseEvidenceDataUrl(dataUrl: string) { const match = /^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(dataUrl); if (!match) throw new Error("Evidence must be a JPEG, PNG, or WebP image"); const buffer = Buffer.from(match[2], "base64"); if (!buffer.length || buffer.length > 10 * 1024 * 1024) throw new Error("Evidence image must be between 1 byte and 10 MB"); return { mimeType: match[1], buffer }; }

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query((opts) => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  hazards: router({ snapshot: publicProcedure.query(() => pilotHazardSnapshot) }),
  weather: router({ hybrid: publicProcedure.query(() => getHybridWeather()) }),
  mapIncidents: router({ submit: publicProcedure.input(z.object({ clientRequestId: z.string().uuid(), category: z.enum(["flooding", "road_blockage", "structural_damage", "medical_sos", "other"]), barangay: z.string().min(2).max(180), summary: z.string().min(5).max(1000), latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), severity: z.enum(["advisory", "watch", "warning", "critical"]), mapConsent: z.enum(["granted", "withheld"]), photo: photoSchema })).mutation(async ({ input }) => { const image = parseEvidenceDataUrl(input.photo.dataUrl); const checksum = createHash("sha256").update(image.buffer).digest("hex"); const ext = image.mimeType === "image/jpeg" ? "jpg" : image.mimeType.split("/")[1]; const stored = await storagePut(`map-incident-evidence/${input.clientRequestId}/${randomUUID()}.${ext}`, image.buffer, image.mimeType); return createMapIncident({ ...input, photo: { objectKey: stored.key, objectUrl: stored.url, mimeType: image.mimeType, byteSize: image.buffer.byteLength, checksum } }); }) }),
  closures: router({ listVerified: publicProcedure.query(() => listVerifiedActiveClosures()), publish: protectedProcedure.input(z.object({ name: z.string().min(3).max(220), barangay: z.string().min(2).max(180), latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), access: z.enum(["use_caution", "restricted", "closed"]), cause: z.string().min(3).max(320), severity: z.enum(["advisory", "watch", "warning", "critical"]), })).mutation(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "LGU authorization is required to publish closure updates." }); return publishVerifiedClosure({ ...input, verifiedBy: ctx.user.id }); }) }),
  safeRoutes: router({ calculate: publicProcedure.input(z.object({ origin: z.object({ latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), label: z.string().min(1).max(120) }), destination: z.object({ latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), label: z.string().min(1).max(120) }) })).query(async ({ input }) => calculateRoadNetworkSafeRoute(input.origin, input.destination, await listVerifiedActiveClosures(), async (origin, destination, detours) => { const payload = await makeRequest<DirectionsResult>("/maps/api/directions/json", { origin: `${origin.latitude},${origin.longitude}`, destination: `${destination.latitude},${destination.longitude}`, mode: "driving", waypoints: detours.length ? detours.map((point) => `${point.latitude},${point.longitude}`).join("|") : undefined, alternatives: false }); const first = payload.routes[0]; return { status: payload.status, encodedPath: first?.overview_polyline.points, ...aggregateRouteLegs(first?.legs ?? []) }; })) }),
  crisisMap: router({ features: publicProcedure.input(z.object({ bbox: z.object({ west: z.number().gte(-180).lte(180), south: z.number().gte(-90).lte(90), east: z.number().gte(-180).lte(180), north: z.number().gte(-90).lte(90) }).refine((bbox) => bbox.west < bbox.east && bbox.south < bbox.north), layers: z.array(z.enum(["weather", "flood", "faultLines", "evacuationCenters", "responseTeams", "roadClosures", "incidents"])).max(7), severities: z.array(z.enum(["advisory", "watch", "warning", "critical"])).max(4).optional() })).query(({ input }) => listCrisisMapFeatures({ ...input.bbox, layers: input.layers, severities: input.severities })) }),
  centers: router({ list: publicProcedure.input(z.object({ latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180) }).optional()).query(({ input }) => listEvacuationCenters(input)), audits: protectedProcedure.input(z.object({ centerId: z.number().int().positive() })).query(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "LGU authorization is required to view publication audit history." }); return listEvacuationCenterAudits(input.centerId); }), updateStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), availableSlots: z.number().int().min(0).max(100000), operationalStatus: z.enum(["open", "limited", "full", "closed"]) })).mutation(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "LGU authorization is required to update center status." }); return updateEvacuationCenterStatus({ ...input, actorId: ctx.user.id }); }), publish: protectedProcedure.input(z.object({ id: z.number().int().positive(), availableSlots: z.number().int().min(0).max(100000), operationalStatus: z.enum(["open", "limited", "full", "closed"]), contactPhone: z.string().max(48).optional(), contactName: z.string().max(160).optional(), medicalSupport: z.string().max(180).optional(), accessibility: z.object({ wheelchair: z.boolean().optional(), medicalSupport: z.union([z.boolean(), z.string()]).optional(), accessibleToilet: z.boolean().optional(), notes: z.string().max(400).optional() }).optional(), sourceName: z.string().min(3).max(180), sourceReference: z.string().max(500).optional(), verificationStatus: z.enum(["reference", "verified", "stale", "retired"]), freshUntil: z.coerce.date().optional(), note: z.string().max(600).optional() })).mutation(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "LGU authorization is required to publish center updates." }); return publishEvacuationCenter({ ...input, actorId: ctx.user.id }); }) }),
  sos: router({ create: publicProcedure.input(z.object({ clientRequestId: z.string().uuid(), category: z.enum(["medical", "rescue_evacuation", "trapped_unsafe", "other"]), priority: z.enum(["high", "critical"]).default("high"), message: z.string().max(280).optional(), locationConsent: z.enum(["granted", "withheld"]), latitude: z.number().gte(-90).lte(90).optional(), longitude: z.number().gte(-180).lte(180).optional(), accuracyMeters: z.number().positive().max(100000).optional() }).superRefine((value, ctx) => { if (value.locationConsent === "granted" && (value.latitude === undefined || value.longitude === undefined)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: "Coordinates are required when location is shared." }); })).mutation(({ input, ctx }) => createSosRequest({ ...input, residentUserId: ctx.user?.id })), status: publicProcedure.input(z.object({ publicReference: z.string().min(6).max(48) })).query(({ input }) => getSosStatus(input.publicReference)) }),
  commandCenter: router({ feed: protectedProcedure.query(({ ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Command-center authorization is required." }); return listCommandCenterFeed(); }), actions: protectedProcedure.input(z.object({ sosRequestId: z.number().int().positive() })).query(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Command-center authorization is required." }); return listSosActions(input.sosRequestId); }), acknowledge: protectedProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Command-center authorization is required." }); return acknowledgeSos({ ...input, actorId: ctx.user.id }); }), assign: protectedProcedure.input(z.object({ id: z.number().int().positive(), assigneeType: z.enum(["lgu", "ngo", "response_team", "other"]), assigneeName: z.string().min(2).max(180), note: z.string().max(600).optional() })).mutation(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Command-center authorization is required." }); return assignSos({ ...input, actorId: ctx.user.id }); }), escalate: protectedProcedure.input(z.object({ id: z.number().int().positive(), note: z.string().min(3).max(600) })).mutation(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Command-center authorization is required." }); return escalateSos({ ...input, actorId: ctx.user.id }); }), resolve: protectedProcedure.input(z.object({ id: z.number().int().positive(), note: z.string().min(3).max(600) })).mutation(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Command-center authorization is required." }); return resolveSos({ ...input, actorId: ctx.user.id }); }), logContact: protectedProcedure.input(z.object({ id: z.number().int().positive(), channel: z.enum(["in_app", "push", "phone", "radio", "other"]), recipientRef: z.string().min(2).max(256), outcome: z.enum(["queued", "reached", "failed", "no_answer"]) })).mutation(({ input, ctx }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Command-center authorization is required." }); return logSosContactAttempt({ ...input, actorId: ctx.user.id }); }) }),
  circles: router({ my: protectedProcedure.query(({ ctx }) => listMyEmergencyCircles(ctx.user.id)), alerts: protectedProcedure.query(({ ctx }) => listMyEmergencyCircleSosAlerts(ctx.user.id)), snapshot: protectedProcedure.input(z.object({ circleId: z.number().int().positive() })).query(({ input, ctx }) => getEmergencyCircleSnapshot({ ...input, userId: ctx.user.id })), create: protectedProcedure.input(z.object({ name: z.string().min(2).max(120), displayName: z.string().min(2).max(160) })).mutation(({ input, ctx }) => createEmergencyCircle({ ...input, userId: ctx.user.id })), join: protectedProcedure.input(z.object({ inviteCode: z.string().min(5).max(32), displayName: z.string().min(2).max(160) })).mutation(({ input, ctx }) => joinEmergencyCircle({ ...input, userId: ctx.user.id })), reviewJoin: protectedProcedure.input(z.object({ circleId: z.number().int().positive(), membershipId: z.number().int().positive(), decision: z.enum(["approve", "reject"]) })).mutation(({ input, ctx }) => reviewEmergencyCircleJoinRequest({ ...input, ownerUserId: ctx.user.id })), rotateInvite: protectedProcedure.input(z.object({ circleId: z.number().int().positive() })).mutation(({ input, ctx }) => rotateEmergencyCircleInviteCode({ ...input, ownerUserId: ctx.user.id })), removeMember: protectedProcedure.input(z.object({ circleId: z.number().int().positive(), membershipId: z.number().int().positive() })).mutation(({ input, ctx }) => removeEmergencyCircleMember({ ...input, ownerUserId: ctx.user.id })), status: protectedProcedure.input(z.object({ circleId: z.number().int().positive(), status: z.enum(["unknown", "safe", "needs_help"]) })).mutation(({ input, ctx }) => updateEmergencyCircleStatus({ ...input, userId: ctx.user.id })), sendSos: protectedProcedure.input(z.object({ circleId: z.number().int().positive(), message: z.string().max(280).optional() })).mutation(({ input, ctx }) => sendEmergencyCircleSos({ ...input, userId: ctx.user.id })), shareLocation: protectedProcedure.input(z.object({ circleId: z.number().int().positive(), latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), accuracyMeters: z.number().positive().max(100000).optional() })).mutation(({ input, ctx }) => shareEmergencyCircleLocation({ ...input, userId: ctx.user.id })), stopLocation: protectedProcedure.input(z.object({ circleId: z.number().int().positive() })).mutation(({ input, ctx }) => stopEmergencyCircleLocation({ ...input, userId: ctx.user.id })) }),
  reports: router({ submit: publicProcedure.input(reportSchema).mutation(async ({ input }) => { const duplicate = await getReportByClientRequestId(input.clientRequestId); if (duplicate) return { id: duplicate.id, status: duplicate.status, idempotent: true }; const image = parseEvidenceDataUrl(input.photo.dataUrl); const checksum = createHash("sha256").update(image.buffer).digest("hex"); const ext = image.mimeType === "image/jpeg" ? "jpg" : image.mimeType.split("/")[1]; const stored = await storagePut(`incident-evidence/${input.clientRequestId}/${randomUUID()}.${ext}`, image.buffer, image.mimeType); const saved = await createIncidentWithEvidence({ ...input, evidence: { objectKey: stored.key, objectUrl: stored.url, originalFilename: input.photo.filename, mimeType: image.mimeType, byteSize: image.buffer.byteLength, checksum } }); await notifyOwner({ title: "New DRRM incident report", content: `${input.category.replace("_", " ")} report received for operational triage.` }); return { id: saved.id, status: saved.status, idempotent: false }; }), recent: protectedProcedure.query(() => listRecentReports()) }),
  family: router({ checkIn: publicProcedure.input(z.object({ status: z.enum(["safe", "needs_help"]), message: z.string().max(280).optional() })).mutation(({ input, ctx }) => queueFamilyCheckin({ ...input, userId: ctx.user?.id })) }),
  volunteers: router({ onboard: publicProcedure.input(z.object({ fullName: z.string().min(2).max(160), contactPhone: z.string().min(7).max(48), barangay: z.string().min(2).max(180), skills: z.array(z.string().min(1).max(80)).min(1).max(12), availability: z.string().min(2).max(100) })).mutation(({ input }) => createVolunteerProfile(input)) }),
  alerts: router({ active: publicProcedure.query(() => listActiveAlerts()), issue: protectedProcedure.input(z.object({ headline: z.string().min(3).max(200), body: z.string().min(3).max(2000), severity: z.enum(["advisory", "watch", "warning", "critical"]), targetName: z.string().min(3).max(200) })).mutation(async ({ input, ctx }) => { const alert = await issueAlert({ ...input, issuedBy: ctx.user.id }); await notifyOwner({ title: `Alert issued: ${input.severity}`, content: `${input.headline} — ${input.targetName}` }); return alert; }) }),
});
export type AppRouter = typeof appRouter;
