import { Construction } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { FormLabel } from "@/components/drrm/DrrmDomain";

export function ClosureUpdateForm({ authenticated, requestLogin }: { authenticated: boolean; requestLogin: () => void }) {
  const utils = trpc.useUtils();
  const [form, setForm] = useState({ name: "", barangay: "", latitude: "11.1086", longitude: "125.3877", access: "restricted" as "use_caution" | "restricted" | "closed", cause: "", severity: "warning" as "advisory" | "watch" | "warning" | "critical" });
  const publish = trpc.closures.publish.useMutation({ onSuccess: () => { toast.success("LGU-verified closure published to the Crisis Map."); void utils.crisisMap.features.invalidate(); void utils.closures.listVerified.invalidate(); setForm((current) => ({ ...current, name: "", cause: "" })); }, onError: (error) => toast.error(error.message || "Closure update could not be published.") });
  const submit = () => { if (!authenticated) { requestLogin(); return; } publish.mutate({ ...form, latitude: Number(form.latitude), longitude: Number(form.longitude) }); };
  return <div className="rounded-2xl border border-[#dbe8e5] bg-[#f8fbfa] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff1ed] text-[#c74335]"><Construction className="h-5 w-5"/></span><div><p className="text-sm font-extrabold text-[#163f4a]">Publish LGU-verified closure</p><p className="text-xs text-[#6d8487]">Only authorized LGU updates are published to routing.</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><FormLabel label="Road / access name"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="h-11 w-full rounded-xl border border-[#dbe8e5] bg-white px-3 text-sm" placeholder="Coastal approach" /></FormLabel><FormLabel label="Barangay"><input value={form.barangay} onChange={(event) => setForm({ ...form, barangay: event.target.value })} className="h-11 w-full rounded-xl border border-[#dbe8e5] bg-white px-3 text-sm" placeholder="Poblacion" /></FormLabel><FormLabel label="Latitude"><input type="number" step="0.0001" value={form.latitude} onChange={(event) => setForm({ ...form, latitude: event.target.value })} className="h-11 w-full rounded-xl border border-[#dbe8e5] bg-white px-3 text-sm" /></FormLabel><FormLabel label="Longitude"><input type="number" step="0.0001" value={form.longitude} onChange={(event) => setForm({ ...form, longitude: event.target.value })} className="h-11 w-full rounded-xl border border-[#dbe8e5] bg-white px-3 text-sm" /></FormLabel><FormLabel label="Access"><select value={form.access} onChange={(event) => setForm({ ...form, access: event.target.value as typeof form.access })} className="h-11 w-full rounded-xl border border-[#dbe8e5] bg-white px-3 text-sm"><option value="use_caution">Use caution</option><option value="restricted">Restricted</option><option value="closed">Closed</option></select></FormLabel><FormLabel label="Severity"><select value={form.severity} onChange={(event) => setForm({ ...form, severity: event.target.value as typeof form.severity })} className="h-11 w-full rounded-xl border border-[#dbe8e5] bg-white px-3 text-sm"><option value="advisory">Advisory</option><option value="watch">Watch</option><option value="warning">Warning</option><option value="critical">Critical</option></select></FormLabel></div><div className="mt-3"><FormLabel label="Closure cause"><input value={form.cause} onChange={(event) => setForm({ ...form, cause: event.target.value })} className="h-11 w-full rounded-xl border border-[#dbe8e5] bg-white px-3 text-sm" placeholder="Flooded carriageway" /></FormLabel></div><button type="button" onClick={submit} disabled={publish.isPending || !form.name || !form.barangay || !form.cause} className="mt-4 w-full rounded-xl bg-[#063448] px-4 py-3 text-sm font-extrabold text-white disabled:opacity-50">{publish.isPending ? "Publishing…" : "Publish verified closure"}</button></div>;
}
