import { Camera, Check, CloudRain, Construction, Download, Filter, MapPinned, Route, ShieldAlert, TriangleAlert, UsersRound, WifiOff, X } from "lucide-react";
import React, { useMemo, useState } from "react";
import { CivilianShell } from "@/components/drrm/CivilianShell";
import { StatusPill } from "@/components/drrm/DrrmPrimitives";
import { DrrmNotice } from "@/components/drrm/DrrmDomain";
import { OpenStreetMapSurface, type CrisisSurfaceFeature } from "@/components/drrm/OpenStreetMapSurface";
import { useCrisisMap, type CrisisLayerKey, type CrisisSeverity } from "@/contexts/CrisisMapContext";
import { buildCrisisDetailSheet } from "@/lib/crisisMapInteractions";
import { crisisSeverityOptions } from "@/lib/crisisMapSeverity";
import { trpc } from "@/lib/trpc";
import { IncidentEvidenceSheet } from "@/components/drrm/IncidentEvidenceSheet";
import { SafeRouteSheet } from "@/components/drrm/SafeRouteSheet";

export const BALANGIGA_SNAPSHOT_URL = "/manus-storage/balangiga-eastern-samar-map-snapshot_0cfd6e60.png";
const layers: { key: CrisisLayerKey; title: string; detail: string; icon: typeof CloudRain; color: string }[] = [
  { key: "weather", title: "PAGASA weather", detail: "Eastern Samar tracking context", icon: CloudRain, color: "text-[#2a8aaf]" },
  { key: "flood", title: "Flood zones", detail: "Balangiga and adjacent areas", icon: ShieldAlert, color: "text-[#3b70b8]" },
  { key: "faultLines", title: "Ground hazards", detail: "Reference layer", icon: MapPinned, color: "text-[#d86a51]" },
  { key: "evacuationCenters", title: "Safe zones", detail: "LGU verification required", icon: MapPinned, color: "text-[#0e715f]" },
  { key: "responseTeams", title: "Response teams", detail: "LGU placeholder pins", icon: UsersRound, color: "text-[#945fb5]" },
  { key: "roadClosures", title: "Road closures", detail: "Barangay access references", icon: Construction, color: "text-[#c74335]" },
  { key: "incidents", title: "Incidents", detail: "Community report references", icon: TriangleAlert, color: "text-[#d08b22]" },
];
const severityCopy: Record<CrisisSeverity, string> = { advisory: "Advisory", watch: "Watch", warning: "Warning", critical: "Critical" };
const bbox = { west: 125.18, south: 10.93, east: 125.68, north: 11.34 };

export default function CrisisMap() {
  const { visible, severities, preset, filterOpen, toggleLayer, toggleSeverity, showAllSeverities, emergencyDefault, clearAll, setFilterOpen } = useCrisisMap();
  const [selected, setSelected] = useState<CrisisSurfaceFeature | null>(null);
  const [evidenceOpen, setEvidenceOpen] = useState(false);
  const [routeOpen, setRouteOpen] = useState(false);
  const [destinationIndex, setDestinationIndex] = useState(0);
  const [routeWaypoints, setRouteWaypoints] = useState<{ latitude: number; longitude: number; label: string }[] | null>(null);
  const activeLayers = useMemo(() => layers.filter((layer) => visible[layer.key]).map((layer) => layer.key), [visible]);
  const queryInput = useMemo(() => ({ bbox, layers: activeLayers, severities }), [activeLayers, severities]);
  const { data = [], isLoading, isError } = trpc.crisisMap.features.useQuery(queryInput);
  const features = data as CrisisSurfaceFeature[];
  const counts = features.reduce<Record<string, number>>((acc, feature) => ({ ...acc, [feature.layer]: (acc[feature.layer] ?? 0) + 1 }), {});

  return <CivilianShell><div className="container pt-5 sm:pt-8">
    <div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-[#589b8d]">Balangiga · Eastern Samar</p><h1 className="font-display mt-1 text-3xl font-extrabold tracking-[-0.055em] sm:text-4xl">Crisis Map</h1><p className="mt-2 max-w-xl text-sm leading-6 text-[#60797d]">Balangiga and adjacent-area weather, hazard, safe-zone, and response reference layers.</p></div><StatusPill tone={isError ? "amber" : "mint"}>{isError ? "Cached data" : "Offline map ready"}</StatusPill></div>
    <section className="relative mt-5 h-[480px] overflow-hidden rounded-[2rem] border border-[#c9ddda] shadow-[0_18px_50px_rgba(6,52,72,0.1)] sm:h-[580px]">
      <OpenStreetMapSurface features={features} onSelect={setSelected} routeWaypoints={routeWaypoints ?? []}/>
      <div className="pointer-events-none absolute left-4 top-4 z-[550] rounded-2xl border border-white/70 bg-white/90 px-3 py-2 shadow-sm"><p className="text-[10px] font-extrabold uppercase tracking-[0.12em] text-[#527176]">Free base map</p><p className="mt-0.5 text-sm font-extrabold text-[#063448]">OpenStreetMap · Balangiga region</p></div>
      <button type="button" onClick={() => setFilterOpen(true)} className="absolute bottom-5 right-5 z-[550] inline-flex h-14 items-center gap-2 rounded-2xl bg-[#063448] px-5 text-sm font-extrabold text-white shadow-[0_10px_28px_rgba(6,52,72,.3)] active:scale-[.97]"><Filter className="h-5 w-5"/>Filters <span className="grid h-5 w-5 place-items-center rounded-full bg-[#87e3c9] text-[10px] text-[#063448]">{activeLayers.length}</span></button>
      <div className="pointer-events-none absolute bottom-5 left-5 z-[550] hidden rounded-2xl border border-white/70 bg-white/90 px-3 py-2 text-xs font-bold text-[#31565c] sm:left-[300px] sm:block"><span className="mr-1.5 inline-block h-2 w-2 rounded-full bg-[#87e3c9]"/>{isLoading ? "Syncing layers…" : `${severities.length} severity level${severities.length === 1 ? "" : "s"} enabled`}</div>
    </section>
    <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_auto_auto]"><DrrmNotice tone="watch"><WifiOff className="mr-2 inline h-4 w-4"/>Save the latest Balangiga regional map before losing signal. Center availability and field conditions still require LGU confirmation.</DrrmNotice><button type="button" onClick={() => setRouteOpen(true)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl border border-[#0e715f] bg-white px-4 text-sm font-extrabold text-[#0e715f]"><Route className="h-4 w-4"/>Find safe route</button><button type="button" onClick={() => setEvidenceOpen(true)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl border border-[#d98978] bg-[#fff5f1] px-4 text-sm font-extrabold text-[#aa4f3f]"><Camera className="h-4 w-4"/>Add photo evidence</button><OfflineMapDownload /></div>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{layers.filter((layer) => visible[layer.key]).map((layer) => { const Icon = layer.icon; return <div key={layer.key} className="rounded-2xl border border-[#dbe8e5] bg-white p-4"><Icon className={`h-5 w-5 ${layer.color}`}/><p className="mt-3 text-xs font-extrabold uppercase tracking-[0.1em] text-[#58787c]">{layer.title}</p><p className="mt-1 text-2xl font-extrabold tracking-[-0.05em]">{isLoading ? "—" : counts[layer.key] ?? 0}</p><p className="mt-1 text-xs text-[#6d8487]">{layer.detail}</p></div>; })}</section>
  </div>{filterOpen && <LayerSheet preset={preset} visible={visible} severities={severities} toggleLayer={toggleLayer} toggleSeverity={toggleSeverity} showAllSeverities={showAllSeverities} emergencyDefault={emergencyDefault} clearAll={clearAll} close={() => setFilterOpen(false)}/>} {selected && <DetailSheet feature={selected} close={() => setSelected(null)}/>} {evidenceOpen && <IncidentEvidenceSheet close={() => setEvidenceOpen(false)}/>} {routeOpen && <SafeRouteSheet destinationIndex={destinationIndex} setDestinationIndex={setDestinationIndex} close={() => setRouteOpen(false)} onRoute={(route) => { setRouteWaypoints(route?.waypoints ?? null); setRouteOpen(false); }}/>}</CivilianShell>;
}

export function DetailSheet({ feature, close }: { feature: CrisisSurfaceFeature; close: () => void }) {
  const detail = buildCrisisDetailSheet(feature);
  const categoryTitle = detail.category === "response-team" ? "Response team" : detail.category === "evacuation-center" ? "Evacuation center" : detail.category === "road-closure" ? "Road closure" : detail.category === "incident" ? "Incident report" : "Map feature";
  const barangay = typeof feature.properties.barangay === "string" ? feature.properties.barangay : null;
  const summary = typeof feature.properties.summary === "string" ? feature.properties.summary : typeof feature.properties.cause === "string" ? feature.properties.cause : null;
  const photoUrl = typeof feature.properties.photoUrl === "string" ? feature.properties.photoUrl : null;
  return <div className="fixed inset-0 z-[70] flex items-end bg-[#063448]/35 sm:items-center sm:justify-center"><section className="max-h-[92dvh] w-full overflow-y-auto rounded-t-[2rem] bg-[#f7fbfa] p-6 shadow-[0_-16px_48px_rgba(6,52,72,.24)] sm:max-w-lg sm:rounded-[2rem]"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#589b8d]">{categoryTitle}</p><h2 className="font-display mt-1 text-2xl font-extrabold tracking-[-0.05em]">{detail.title}</h2></div><button type="button" onClick={close} aria-label="Close detail sheet" className="grid h-11 w-11 place-items-center rounded-2xl border border-[#d7e4e1] bg-white"><X className="h-5 w-5"/></button></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-white p-3"><span className="block text-xs font-bold text-[#628085]">Status</span><strong className="mt-1 block capitalize">{detail.statusLabel}</strong></div><div className="rounded-xl bg-white p-3"><span className="block text-xs font-bold text-[#628085]">Updated</span><strong className="mt-1 block">Feed snapshot</strong></div>{barangay && <div className="rounded-xl bg-white p-3"><span className="block text-xs font-bold text-[#628085]">Barangay / area</span><strong className="mt-1 block">{barangay}</strong></div>}{detail.availableSlots !== null && <div className="rounded-xl bg-white p-3"><span className="block text-xs font-bold text-[#628085]">Available slots</span><strong className="mt-1 block">{detail.availableSlots}</strong></div>}{summary && <div className="col-span-2 rounded-xl border border-[#dbe8e5] bg-white p-3 text-sm text-[#46676c]"><strong className="text-[#163f4a]">Report detail. </strong>{summary}</div>}{photoUrl && <a href={photoUrl} target="_blank" rel="noreferrer" className="col-span-2 overflow-hidden rounded-2xl border border-[#dbe8e5] bg-white"><img src={photoUrl} alt="Resident incident evidence" className="h-48 w-full object-cover"/><span className="block p-3 text-sm font-extrabold text-[#0e715f]">View resident photo evidence</span></a>}{detail.showPlaceholderNotice && <div className="col-span-2 rounded-xl border border-[#e7c98a] bg-[#fff8e7] p-3 text-sm text-[#6e5313]"><strong>Placeholder position.</strong> Confirm live deployment status with the LGU operations desk before acting.</div>}</div></section></div>;
}

export function OfflineMapDownload() { return <a href={BALANGIGA_SNAPSHOT_URL} download="harborline-balangiga-eastern-samar-offline-map.png" aria-label="Save Balangiga offline map" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-[#0e715f] px-4 text-sm font-extrabold text-white shadow-[0_8px_20px_rgba(14,113,95,.2)] active:scale-[.97]"><Download className="h-4 w-4"/>Save map</a>; }

export function LayerSheet({ preset, visible, severities, toggleLayer, toggleSeverity, showAllSeverities, emergencyDefault, clearAll, close }: { preset: string; visible: Record<CrisisLayerKey, boolean>; severities: CrisisSeverity[]; toggleLayer: (key: CrisisLayerKey) => void; toggleSeverity: (severity: CrisisSeverity) => void; showAllSeverities: () => void; emergencyDefault: () => void; clearAll: () => void; close: () => void }) {
  return <div className="fixed inset-0 z-[60] flex items-end bg-[#063448]/35 p-0 sm:items-center sm:justify-center sm:p-6"><section className="w-full rounded-t-[2rem] bg-[#f7fbfa] p-5 shadow-[0_-16px_48px_rgba(6,52,72,.24)] sm:max-w-lg sm:rounded-[2rem]"><div className="flex items-center justify-between"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-[#589b8d]">Clutter management</p><h2 className="font-display mt-1 text-2xl font-extrabold tracking-[-0.05em]">Map filters</h2></div><button type="button" onClick={close} aria-label="Close map filters" className="grid h-11 w-11 place-items-center rounded-2xl border border-[#d7e4e1] bg-white"><X className="h-5 w-5"/></button></div><div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={emergencyDefault} className={`rounded-xl px-4 py-3 text-sm font-extrabold ${preset === "emergency" ? "bg-[#0e715f] text-white" : "border border-[#b9d5ce] bg-white text-[#0e715f]"}`}>Emergency Default</button><button type="button" onClick={clearAll} className={`rounded-xl px-4 py-3 text-sm font-extrabold ${preset === "clear" ? "bg-[#063448] text-white" : "border border-[#d7e4e1] bg-white text-[#46676c]"}`}>Clear all</button></div><div className="mt-5"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold text-[#163f4a]">Crisis severity</p><p className="mt-0.5 text-xs text-[#6d8487]">Applies to hazards and safe zones.</p></div><button type="button" onClick={showAllSeverities} className="text-xs font-extrabold text-[#0e715f]">Show all</button></div><div className="mt-3 grid grid-cols-2 gap-2">{crisisSeverityOptions.map((severity) => <button key={severity} type="button" aria-pressed={severities.includes(severity)} onClick={() => toggleSeverity(severity)} className={`rounded-xl border px-3 py-2 text-left text-sm font-extrabold ${severities.includes(severity) ? "border-[#0e715f] bg-[#e4f5ef] text-[#0e715f]" : "border-[#d7e4e1] bg-white text-[#6d8487]"}`}><span className={`mr-2 inline-block h-2 w-2 rounded-full ${severity === "critical" ? "bg-[#d95d4f]" : severity === "warning" ? "bg-[#d08b22]" : severity === "watch" ? "bg-[#3178b7]" : "bg-[#89a4a0]"}`}/>{severityCopy[severity]}</button>)}</div></div><div className="mt-5 space-y-2">{layers.map((layer) => { const Icon = layer.icon; return <button type="button" key={layer.key} onClick={() => toggleLayer(layer.key)} className="flex w-full items-center justify-between rounded-2xl border border-[#dbe8e5] bg-white px-4 py-3 text-left"><span className="flex items-center gap-3"><Icon className={`h-5 w-5 ${layer.color}`}/><span><strong className="block text-sm">{layer.title}</strong><small className="text-xs text-[#6d8487]">{layer.detail}</small></span></span><span className={`grid h-6 w-6 place-items-center rounded-full ${visible[layer.key] ? "bg-[#0e715f] text-white" : "bg-[#e4eeeb] text-transparent"}`}><Check className="h-4 w-4"/></span></button>; })}</div></section></div>;
}
